// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>FT_HTMLTest_Shared_Dataset</b><br>
 * Generated     : <b>2020/04/14 9:54:55 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  April 14, 2020
 * @author Administrator
 */
public abstract class FT_HTMLTest_Shared_DatasetHelper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * ContestPage: with default state.
	 *		.class : Html.HtmlDocument
	 * 		.title : Contest page
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/visionofficeproducts/conte ...
	 */
	protected DocumentTestObject document_contestPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_contestPage"));
	}
	/**
	 * ContestPage: with specific test context and state.
	 *		.class : Html.HtmlDocument
	 * 		.title : Contest page
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/visionofficeproducts/conte ...
	 */
	protected DocumentTestObject document_contestPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_contestPage"), anchor, flags);
	}
	
	/**
	 * VTIGROUP0: with default state.
	 *		.text : 
	 * 		.id : 
	 * 		.type : hidden
	 * 		.value : 0
	 * 		.class : Html.INPUT.hidden
	 * 		.title : 
	 * 		.name : VTI-GROUP
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_vtigrouP0() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_vtigrouP0"));
	}
	/**
	 * VTIGROUP0: with specific test context and state.
	 *		.text : 
	 * 		.id : 
	 * 		.type : hidden
	 * 		.value : 0
	 * 		.class : Html.INPUT.hidden
	 * 		.title : 
	 * 		.name : VTI-GROUP
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_vtigrouP0(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_vtigrouP0"), anchor, flags);
	}
	
	/**
	 * position: with default state.
	 *		.text : Please select from below Professional Staff Management Senior Management Preside ...
	 * 		.id : 
	 * 		.class : Html.SELECT
	 * 		.title : 
	 * 		.name : position
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_position() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_position"));
	}
	/**
	 * position: with specific test context and state.
	 *		.text : Please select from below Professional Staff Management Senior Management Preside ...
	 * 		.id : 
	 * 		.class : Html.SELECT
	 * 		.title : 
	 * 		.name : position
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_position(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_position"), anchor, flags);
	}
	
	/**
	 * salary: with default state.
	 *		.text : Please select from below Under $25,000 $25,001 to $50,000 $50,001 to $75,000 $75 ...
	 * 		.id : 
	 * 		.class : Html.SELECT
	 * 		.title : 
	 * 		.name : salary
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_salary() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_salary"));
	}
	/**
	 * salary: with specific test context and state.
	 *		.text : Please select from below Under $25,000 $25,001 to $50,000 $50,001 to $75,000 $75 ...
	 * 		.id : 
	 * 		.class : Html.SELECT
	 * 		.title : 
	 * 		.name : salary
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_salary(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_salary"), anchor, flags);
	}
	
	/**
	 * buyerno: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : no
	 * 		.class : Html.INPUT.radio
	 * 		.title : 
	 * 		.name : buyer
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject radioButton_buyerno() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_buyerno"));
	}
	/**
	 * buyerno: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : no
	 * 		.class : Html.INPUT.radio
	 * 		.title : 
	 * 		.name : buyer
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject radioButton_buyerno(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_buyerno"), anchor, flags);
	}
	
	/**
	 * address: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : 
	 * 		.name : address
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_address() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_address"));
	}
	/**
	 * address: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : 
	 * 		.name : address
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_address(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_address"), anchor, flags);
	}
	
	/**
	 * buyerDescription: with default state.
	 *		.id : 
	 * 		.class : Html.TEXTAREA
	 * 		.title : 
	 * 		.name : buyer description
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_buyerDescription() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_buyerDescription"));
	}
	/**
	 * buyerDescription: with specific test context and state.
	 *		.id : 
	 * 		.class : Html.TEXTAREA
	 * 		.title : 
	 * 		.name : buyer description
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_buyerDescription(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_buyerDescription"), anchor, flags);
	}
	
	/**
	 * City: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : 
	 * 		.name : City
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_city() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_city"));
	}
	/**
	 * City: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : 
	 * 		.name : City
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_city(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_city"), anchor, flags);
	}
	
	/**
	 * email: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : 
	 * 		.name : email
	 * 		.classIndex : 5
	 */
	protected TextGuiTestObject text_email() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_email"));
	}
	/**
	 * email: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : 
	 * 		.name : email
	 * 		.classIndex : 5
	 */
	protected TextGuiTestObject text_email(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_email"), anchor, flags);
	}
	
	/**
	 * Name: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : 
	 * 		.name : Name
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_name() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_name"));
	}
	/**
	 * Name: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : 
	 * 		.name : Name
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_name(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_name"), anchor, flags);
	}
	
	/**
	 * State: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : 
	 * 		.name : State
	 * 		.classIndex : 3
	 */
	protected TextGuiTestObject text_state() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_state"));
	}
	/**
	 * State: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : 
	 * 		.name : State
	 * 		.classIndex : 3
	 */
	protected TextGuiTestObject text_state(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_state"), anchor, flags);
	}
	
	/**
	 * Zip: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : 
	 * 		.name : Zip
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject text_zip() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_zip"));
	}
	/**
	 * Zip: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : 
	 * 		.name : Zip
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject text_zip(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_zip"), anchor, flags);
	}
	
	

	protected FT_HTMLTest_Shared_DatasetHelper()
	{
		setScriptName("FT_HTMLTest_Shared_Dataset");
	}
	
}

